env:
  es2021: true
  browser: true,
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: [error, ignorePackages],
  import/prefer-default-export: off,
  no-param-reassign: off,
  implicit-arrow-linebreak: off,
  no-use-before-define: off,
}
